import os
import json
import glob
import argparse
import asyncio
from collections import defaultdict
from tqdm.asyncio import tqdm
from openai import AsyncOpenAI

# Set up predefined error categories
ERROR_CATEGORIES = [
    "pronoun_failure", "attributive_misid", "noise_distraction",
    "context_loss", "action_ordering", "action_omission",
    "hallucinated_action", "wrong_destination", "other"
]

SYSTEM_PROMPT = f"""You are an expert robotics judge evaluating an LLM agent's generated plans.
You will be provided with:
1. Instruction: The task given to the agent.
2. Target Object: The correct object the agent should manipulate.
3. Ground Truth Plan: The correct sequence of actions.
4. Generated Plan: The sequence of actions generated by the agent.

The agent's generated plan failed. Your task is to analyze the failure and provide:
1. error_category: Must be exactly one of {ERROR_CATEGORIES}.
2. reason: A concise explanation (1-2 sentences max) of why this specific error category applies and what went wrong.

Return your response strictly as a JSON object with keys "error_category" and "reason"."""

async def evaluate_single_failure(client, sem, example, model_name):
    """Evaluate a single failed example using OpenAI API with concurrency limit."""
    async with sem:
        try:
            prompt = f"""
Instruction: {example.get('instruction', 'N/A')}
Target Object: {example.get('target_object', 'N/A')}
Ground Truth Plan: {example.get('ground_truth_plan', [])}
Generated Plan: {example.get('generated_plan', [])}
"""
            response = await client.chat.completions.create(
                model=model_name,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": prompt}
                ],
                response_format={"type": "json_object"},
                temperature=0.0,
                max_tokens=150
            )
            
            result_json = json.loads(response.choices[0].message.content)
            
            # Ensure valid category
            cat = result_json.get("error_category", "other")
            if cat not in ERROR_CATEGORIES:
                cat = "other"
                
            return {
                "example_id": example.get("example_id", "unknown"),
                "task_type": example.get("task_type", "unknown"),
                "error_category": cat,
                "reason": result_json.get("reason", "No reason provided.")
            }
        except Exception as e:
            return {
                "example_id": example.get("example_id", "unknown"),
                "task_type": example.get("task_type", "unknown"),
                "error_category": "api_error",
                "reason": f"API Error: {str(e)}"
            }

async def process_model_results(client, model_dir, results_file, judge_model, concurrency):
    """Process all failures for a single model's results file."""
    model_name = os.path.basename(model_dir)
    print(f"\nProcessing results for model: {model_name}")
    
    with open(results_file, "r") as f:
        data = json.load(f)
        
    failures = []
    if "detailed_results" in data:
        for condition, results_list in data["detailed_results"].items():
            for result in results_list:
                if not result.get("success", True):
                    failures.append(result)
                    
    if not failures:
        print(f"No failures found for {model_name}.")
        return

    print(f"Found {len(failures)} failures to analyze.")
    
    # Run async evaluation
    sem = asyncio.Semaphore(concurrency)
    tasks = [evaluate_single_failure(client, sem, f, judge_model) for f in failures]
    
    # Execute with progress bar
    evaluated = await tqdm.gather(*tasks, desc=f"Evaluating {model_name}")
    
    # Calculate statistics
    category_counts = defaultdict(int)
    for res in evaluated:
        category_counts[res["error_category"]] += 1
        
    total = len(evaluated)
    percentages = {cat: round((count / total) * 100, 2) for cat, count in category_counts.items()}
    
    # Output the report
    report = {
        "model": model_name,
        "total_failures": total,
        "error_category_percentages": percentages,
        "detailed_evaluations": evaluated
    }
    
    report_file = os.path.join(model_dir, f"{model_name}_llmjudge.json")
    with open(report_file, "w") as f:
        json.dump(report, f, indent=2)
        
    print(f"\n{model_name} Error Breakdown:")
    for cat, pct in sorted(percentages.items(), key=lambda x: -x[1]):
        print(f"  - {cat:<25} {pct:>5.1f}%")
    print(f"Saved detailed analysis to {report_file}")


async def main():
    parser = argparse.ArgumentParser(description="Use an LLM to judge model failures.")
    parser.add_argument("--api-key", type=str, required=True, help="OpenAI API Key")
    parser.add_argument("--judge-model", type=str, default="gpt-4o", help="OpenAI model to use as judge")
    parser.add_argument("--model", type=str, default=None, help="Specific model folder to analyze (e.g., '1B' or 'Qwen3-8B')")
    parser.add_argument("--results-dir", type=str, default="phase1/results", help="Directory containing results")
    parser.add_argument("--concurrency", type=int, default=50, help="Max concurrent API calls")
    args = parser.parse_args()

    client = AsyncOpenAI(api_key=args.api_key)
    
    # Find result files
    if args.model:
        result_files = glob.glob(os.path.join(args.results_dir, args.model, "*.json"))
    else:
        result_files = glob.glob(os.path.join(args.results_dir, "*/*.json"))
        
    result_files = [f for f in result_files if "results_" in os.path.basename(f) and "metadata" not in f]
    
    for results_file in result_files:
        model_dir = os.path.dirname(results_file)
        await process_model_results(client, model_dir, results_file, args.judge_model, args.concurrency)

if __name__ == "__main__":
    asyncio.run(main())
